### ISSUE TITLE
[Feat] web 서비스의 page 단위를 나눠서 구성

### ISSUE THREAD

**Issue by nerdchanii** [chatty-potato/1take.web#13]
## 요구사항

- react-router-dom을 이용해서 page 단위를 나눠주세요.
- 
## 작업사항

- [ ] /page폴더 하위에 page단위가 될 컴포넌트들을 삽입해주세요.
- [ ] Page단위를 나누고, 몇몇 결정들을 위해서 잠깐 회의하는 시간이 필요할 듯 합니다. @rheefine
- 필요한 페이지(화면)들은 다음과 같습니다. 
  - 홈페이지
  - 면접 팁 페이지
  - 약관페이지
    - 서비스 이용약관
    - 서비스 정책
   
  - 로그인페이지
  
  - 인터뷰관련 페이지
    - 인터뷰 대기실 
    - 면접사전 설정 페이지(카테고리 설정등)
    - 면접 페이지
    - 면접 결과페이지
    - 북마크 페이지
    
  - 마이페이지
  - 북마크 페이지
  - 문의하기 폼 혹은 페이지
  - 탈퇴페이지

## Ref 
- 팀 피그마를 참조

**Comment by nerdchanii** [comment]
각 페이지의 라우팅 경로는 다음과 같이 임의로 설정했습니다. 이 기능이 합쳐지기 전에 회의를 통해서 경로를 수정해야할 수 있습니다.

- 홈페이지 - /
- 면접 팁 페이지 - /tips-for-interview
  - 추후의 페이지가 많아지면, 팁마다 라우팅 태워주면 좋을 듯 싶네요.
- 약관페이지들 
  - 서비스 이용약관 /policy/term-of-service
  - 서비스 정책안내 /policy/service
  - 개인정보처리방침 /policy/privacy
- 로그인페이지 /login
- 인터뷰관련 페이지 
  - 인터뷰 대기실 /interview
  - 면접사전 설정 페이지(카테고리 설정등) /interview/set-up
  - 면접 페이지 /interview/{sessionId}
  - 면접 결과페이지 /interview/result/{sessionId}
- 북마크 페이지 /interview/bookmarks
- 마이페이지 /mypage
- 문의하기 폼 혹은 페이지 /customer-service/inquiry 
  // 문의하기의 경우 노션쪽으로 연결시켜서 노션으로 구성하는 것도 방법이 될 것 같습니다.
- 탈퇴페이지 -> 페이지로 구성할지 modal로 마이페이지쪽에서 끝낼지 고민해봐야합니다.

**Comment by rheefine** [comment]
화원가입 정보 입력 페이지 같은 경우는 designer의 방향성을 따라가되 만약 없다면 하나의 라우팅 페이지로 생각하는 것이 좋을 것 같습니다.

**Comment by nerdchanii** [comment]
> 화원가입 정보 입력 페이지 같은 경우는 designer의 방향성을 따라가되 만약 없다면 하나의 라우팅 페이지로 생각하는 것이 좋을 것 같습니다.

@rheefine 확인했습니당. 해당 코멘트 레퍼런스 이슈로 생성해놓고 추후에 작업하겠습니다.

**Comment by nerdchanii** [comment]
#14 에서 해결했습니다.
